import VanillaPage from '@/components/VanillaPage';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "AI BMR Calculator - Prabha Wellness",
};

const html = "\n\n    <div class=\"feature-container\">\n        <div class=\"feature-card\" data-aos=\"zoom-in\">\n            <h1>AI BMR Calculator</h1>\n            <p style=\"color:#666; margin-bottom:20px;\">Calculate calories &amp; get AI metabolism advice.</p>\n\n            <form id=\"bmrForm\" onsubmit=\"calculateBMR(event)\">\n                <select id=\"gender\"><option value=\"male\">Male</option><option value=\"female\">Female</option></select>\n                <input type=\"number\" id=\"age\" placeholder=\"Age (Years)\" required=\"\">\n                <input type=\"number\" id=\"weight\" placeholder=\"Weight (KG)\" required=\"\">\n                <input type=\"number\" id=\"height\" placeholder=\"Height (CM)\" required=\"\">\n                <button type=\"submit\" class=\"calc-btn\">Calculate &amp; Ask AI</button>\n            </form>\n\n            <div id=\"resultBox\" style=\"display:none; margin-top:30px;\">\n                <p>Your Daily BMR</p>\n                <div class=\"bmi-value\" id=\"bmrValue\">--</div>\n                <p>Calories / Day</p>\n\n                <!-- AI Section -->\n                <div id=\"aiBox\" class=\"ai-insight-box\">\n                    <strong><i class=\"fas fa-robot\"></i> AI Metabolism Insight:</strong><br>\n                    <span id=\"aiText\">Analyzing your metabolism<span class=\"loading-dots\"></span></span>\n                </div>\n            </div>\n        </div>\n    </div>\n\n    \n    \n\n\n";
const scripts: string[] = ["https://unpkg.com/aos@2.3.1/dist/aos.js"];
const inlineScripts: string[] = ["\n        AOS.init();\n\n        async function calculateBMR(e) {\n            e.preventDefault();\n            const gender = document.getElementById('gender').value;\n            const age = document.getElementById('age').value;\n            const weight = document.getElementById('weight').value;\n            const height = document.getElementById('height').value;\n\n            // 1. Calculate BMR (Mifflin-St Jeor)\n            let bmr = (10 * weight) + (6.25 * height) - (5 * age) + (gender === 'male' ? 5 : -161);\n            bmr = Math.round(bmr);\n\n            // Show Result\n            document.getElementById('bmrValue').innerText = bmr;\n            document.getElementById('resultBox').style.display = 'block';\n            \n            // Show Loading\n            const aiBox = document.getElementById('aiBox');\n            const aiText = document.getElementById('aiText');\n            aiBox.style.display = 'block';\n            aiText.innerHTML = 'Analyzing your metabolism<span class=\"loading-dots\"></span>';\n\n            // 2. Call AI Backend\n            try {\n                const response = await fetch('/.netlify/functions/fetch-diet', {\n                    method: 'POST',\n                    body: JSON.stringify({ \n                        type: 'bmr',  // <-- Yeh bata raha hai ki BMR logic use karo\n                        data: { gender, age, bmrValue: bmr } \n                    })\n                });\n\n                const result = await response.json();\n                if(result.reply) {\n                    aiText.innerText = result.reply;\n                } else {\n                    aiText.innerText = \"Tip: Drink more water to boost metabolism.\";\n                }\n\n            } catch (error) {\n                console.error(error);\n                aiText.innerText = \"Connection failed. Eat healthy!\";\n            }\n        }\n    "];
const styles: string[] = ["\n        :root {\n            --primary-neon: #00E676; --primary-dark: #004D40;\n            --glass-bg: rgba(255, 255, 255, 0.65); --bg-body: #f0fdf4;\n        }\n        * { margin:0; padding:0; box-sizing:border-box; font-family:'Outfit',sans-serif; }\n        body { background: var(--bg-body); min-height: 100vh; padding: 20px; }\n\n        .feature-container { max-width: 550px; margin: 40px auto; }\n        .feature-card {\n            background: var(--glass-bg); backdrop-filter: blur(20px);\n            border-radius: 30px; padding: 40px; text-align: center;\n            box-shadow: 0 15px 35px rgba(0,0,0,0.05);\n        }\n\n        .bmi-value {\n            font-size: 3.5rem; font-weight: 800; color: var(--primary-dark);\n            margin: 10px 0;\n        }\n\n        .ai-insight-box {\n            background: rgba(0, 230, 118, 0.1);\n            border-left: 4px solid var(--primary-neon);\n            padding: 15px; margin-top: 20px; text-align: left;\n            border-radius: 10px; font-size: 0.95rem; line-height: 1.5; color: #004D40;\n            display: none; animation: fadeIn 0.5s;\n        }\n        \n        .loading-dots:after {\n            content: '.'; animation: dots 1.5s steps(5, end) infinite;\n        }\n        @keyframes dots { 0%, 20% { content: '.'; } 40% { content: '..'; } 60% { content: '...'; } 100% { content: ''; } }\n        @keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }\n\n        /* Reuse previous CSS for Inputs/Buttons */\n        input, select { width: 100%; padding: 15px; margin-bottom: 15px; border-radius: 15px; border:1px solid #ddd; }\n        .calc-btn { width: 100%; padding: 15px; background: #1f2937; color: white; border-radius: 50px; cursor: pointer; border: none; font-weight: 700; }\n        .calc-btn:hover { background: var(--primary-neon); color: black; }\n    "];

export default function Page() {
  return (
    <>
      {styles.map((css, i) => <style key={i} dangerouslySetInnerHTML={{ __html: css }} />)}
      <VanillaPage html={html} scripts={scripts} inlineScripts={inlineScripts} />
    </>
  );
}
